# Generated by Django 4.2.30 on 2026-07-05 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_dispositivorecordado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('E', 'Efectivo'), ('N', 'Nequi'), ('B', 'Bancolombia'), ('O', 'Otros Bancos')], help_text='Método de pago usado en la venta (solo para tipo S).', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='precio_unitario_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta unitario al momento de la venta (solo tipo S vía POS).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='siguiente_numero_factura',
            field=models.PositiveIntegerField(default=1, help_text='Próximo número de factura a asignar para este negocio.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='favorito',
            field=models.BooleanField(default=False, help_text='Marca el producto como favorito para filtros rápidos.'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.PositiveIntegerField(blank=True, editable=False, help_text='Consecutivo de factura, único dentro del negocio.', null=True)),
                ('cliente_nombre', models.CharField(blank=True, help_text='Nombre del cliente (opcional)', max_length=200, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en moneda local (valor absoluto)', max_digits=12)),
                ('iva', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (19, '19%')], default=19, help_text='IVA aplicado a la venta')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, help_text='Suma de precio_venta * cantidad antes de descuento/IVA', max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, help_text='Resultado después de aplicar descuento e IVA', max_digits=12)),
                ('payment_method', models.CharField(choices=[('E', 'Efectivo'), ('N', 'Nequi'), ('B', 'Bancolombia'), ('O', 'Otros Bancos')], default='E', help_text='Método de pago usado en la venta completa', max_length=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app.negocio')),
                ('usuario', models.ForeignKey(blank=True, help_text='Bodeguero que realizó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='app.venta'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(fields=('negocio', 'numero_factura'), name='unique_numero_factura_por_negocio'),
        ),
    ]
