# Generated by Django 4.2.30 on 2026-08-03 02:00
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_movimientoinventario_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='siguiente_numero_factura',
            field=models.PositiveIntegerField(default=1, help_text='Próximo número de factura a asignar para este negocio.'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='precio_unitario_venta',
            field=models.DecimalField(blank=True, null=True, max_digits=12, decimal_places=2, help_text='Precio de venta unitario al momento de la venta (solo tipo S vía POS).'),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.PositiveIntegerField(blank=True, null=True, editable=False, help_text='Consecutivo de factura, único dentro del negocio.'),
        ),
    ]
